# Generated by Django 2.2.5 on 2019-09-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32, verbose_name='title')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('plan_today', models.CharField(max_length=512, verbose_name='Plan Today')),
                ('did_today', models.CharField(max_length=512, verbose_name='Did Today')),
                ('plan_tom', models.CharField(max_length=512, verbose_name='Plan tomorrow')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal_entry.Journal')),
            ],
        ),
    ]
