# Generated by Django 2.2.5 on 2019-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=22, verbose_name='name'),
        ),
    ]
