# Generated by Django 2.2.5 on 2019-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0002_auto_20191002_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='did_today',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='plan_today',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='plan_tom',
            field=models.TextField(),
        ),
    ]
