# Generated by Django 2.2.5 on 2019-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0003_auto_20191011_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
