# Generated by Django 2.2.5 on 2019-10-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0004_auto_20191014_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
