# Generated by Django 2.2.5 on 2019-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0005_auto_20191015_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Title', max_length=32, unique=True, verbose_name='title'),
        ),
    ]
