# Generated by Django 2.2.5 on 2019-10-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0006_auto_20191015_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Title', max_length=32, verbose_name='title'),
        ),
    ]
