# Generated by Django 2.2.5 on 2019-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0007_auto_20191015_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
