# Generated by Django 2.2.5 on 2019-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entry', '0008_auto_20191015_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
