# Generated by Django 2.2.5 on 2019-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('email', models.CharField(max_length=54, verbose_name='email')),
                ('password', models.CharField(max_length=256, unique=True, verbose_name='password')),
            ],
        ),
    ]
