# Generated by Django 2.2.5 on 2019-09-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
