# Generated by Django 2.2.5 on 2019-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190926_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=54, unique=True, verbose_name='email'),
        ),
    ]
